### ISSUE TITLE
Issues with v0.1.4

### ISSUE THREAD

**Issue by Desperationis** [dbaldwin/go1-js#5]
I was following along the *awesome* youtube tutorials on controlling the Go1 with JS and noticed that they did not work at all with v1.4.

Specifically, I don't see the "connecting" and "connected" messages being displayed to the console when on the same network as the Go1. I still see the output of commands, but it seems as though the script never connects to Go1. 

npm version: 9.5.1
node version: 18.16.0
go1-js version: 0.1.4

When running, I use `node ./index.js` after slightly modifying the example scripts to import from `@droneblocks/go1-js` and removing typescript-specific syntax. I'm relatively new to JS, and I would not be surprised if this issue was because of how I run the script.

**Comment by dbaldwin** [comment]
Thanks for reporting this issue. Will take a look first thing in the
morning and let you know what we find out.

**Comment by dbaldwin** [comment]
@Desperationis this was an oversight on our part. We added a new requirement to in v0.1.4 to initialize the robot like this:

```
let dog = new Go1();
dog.init();
// your commands below
```

I've updated the README and examples to reflect this change:

https://github.com/dbaldwin/go1-js/blob/main/README.md

Please test and verify at your convenience. Then we'll close this out. Thank you.

**Comment by Desperationis** [comment]
Sounds good, I'll check it out this evening. Thank you.

**Comment by Desperationis** [comment]
Yep, missing `init()` was the issue. Issue closed.
